"""Market-engine universe seeds and archetype classification."""

from __future__ import annotations


ARCHETYPE_MEGA = "Mega"
ARCHETYPE_LARGE = "Large"
ARCHETYPE_MID = "Mid"
ARCHETYPE_SMALL = "Small"
ARCHETYPE_MICRO = "Micro"
ARCHETYPE_MEME = "Meme"
ARCHETYPE_SPECIAL_SITUATION = "Special Situation"

MARKET_ARCHETYPES = (
    ARCHETYPE_MEGA,
    ARCHETYPE_LARGE,
    ARCHETYPE_MID,
    ARCHETYPE_SMALL,
    ARCHETYPE_MICRO,
    ARCHETYPE_MEME,
    ARCHETYPE_SPECIAL_SITUATION,
)

MEME_TICKERS = {
    "AMC", "BB", "BYND", "CHPT", "CVNA", "DJT", "FUBO", "GME", "HOOD", "MARA",
    "NIO", "OPEN", "PLTR", "RIVN", "RIOT", "SOFI", "UPST",
}

SPECIAL_SITUATION_TICKERS = {
    "AFRM", "AI", "COIN", "DNA", "ENPH", "ENVX", "GRRR", "IONQ", "LCID", "LMND",
    "PI", "RKT", "RUN", "SMCI", "STEM", "WBD",
}

QQQ_EXPANSION_TICKERS = (
    "AAPL MSFT NVDA AMZN META AVGO GOOGL GOOG TSLA COST NFLX AMD PEP ADBE CSCO TMUS "
    "INTU QCOM TXN AMAT CMCSA AMGN HON ISRG BKNG SBUX ADP GILD MDLZ LRCX REGN PANW "
    "VRTX MU KLAC MELI SNPS CDNS CRWD MAR CSX ORLY ABNB CTAS MNST FTNT NXPI PDD AEP "
    "ROST PAYX ODFL PCAR CPRT KDP EXC CEG FAST EA DDOG GEHC XEL TEAM BKR MRVL FANG "
    "ZS ANSS IDXX DXCM LULU MCHP ON WBD BIIB GFS ARM MDB DLTR ILMN WBA SIRI LCID "
    "TTD CHTR CDW VRSK AZN LIN ASML ADI PYPL SPLK OKTA RIVN"
).split()

SP500_EXPANSION_TICKERS = (
    "AAPL MSFT NVDA AMZN META GOOGL GOOG BRK-B LLY JPM AVGO XOM UNH V PG MA COST HD "
    "WMT NFLX BAC ABBV KO CRM CVX ORCL MRK AMD ADBE PEP TMO LIN ACN MCD CSCO IBM ABT "
    "GE QCOM DIS DHR INTU VZ AMAT TXN CMCSA CAT PM NOW ISRG UBER PFE RTX AMGN SPGI "
    "NEE LOW HON COP UNP BKNG GS PLD ETN T DE BLK SYK TJX BSX LMT MDT ELV ADP PANW "
    "VRTX GILD ADI CB SBUX MMC MU BMY KLAC REGN MDLZ FI LRCX SCHW C CI SO ZTS CVS "
    "ANET EQIX PGR ICE DUK SHW MO WM CL APH TT PH AMT CME CDNS SNPS EOG CMG NOC MCO "
    "USB ORLY TDG ITW MSI HCA AON GD CEG MMM PNc MAR EMR APD WELL CTAS AJG FCX ECL "
    "TGT WMB COF CSX PYPL NXPI RSG CARR NSC GM AZO ADSK OKE HLt TRV AFL SPG FDX "
    "ROST BK MET KMI SRE DHI MPC O AEP JCI PSA ALL URI VLO PSA MCHP GWW TEL DLTR "
    "AIG FICO MNST FTNT ODFL PCAR COR KDP CPRT MSCI HES LEN NEM PWR AMP RCL CCI "
    "FANG DOW PAYX LHX KMB NUE OXY STZ PRU FAST KHC EW CTVA VRSK EXC GIS IQV PEG "
    "CTSH IR KR YUM KVUE GEHC SYY EA RMD ACGL CMI IDXX MLM DD VMC ADM DFS HWM "
    "HIG EFX ON BIIB FIS XYL EXR WAB EIX TSCO LYB PCG ROK CSCO TRGP CDW HPQ ANSS "
    "HAL FSLR DVN GPN WST AVB NDAQ KEYS DOV MTB WEC PPG EBAY TROW AWK CHD DAL "
    "BRO NTAP FITB DTE GRMN BR SWK PHM CAH ETR WY TYL HPE STT STE SBAC HUBB VTR "
    "EQR PPL WDC RF CBOE FE DRI ES AEE VLTO PTC WAT BALL HBAN EL CINF INVH IFF "
    "TER MKC CLX HOLX LH LUV COO CMS TSN NTRS MOH EXPE CFG J JBL BBY MAS TXT "
    "OMC ARE MAA LDOS ZBH CNP SYF DGX EPAM FDS ESS VRSN ALB PODD K L NTES WRB "
    "AKAM CE PKG FOXA FOX NWSA NWS GEN IP DPZ TRMB SNA KEY STX UAL AES LKQ "
    "POOL INCY ENPH APA APTV CRL SWKS NDSN QRVO CF BG MRNA TECH BAX EMN WBA "
    "BEN HST AOS MTCH CZR HAS PARA ETSY BWA PAYC SEDG ROL TFX BIO XRAY GNRC "
    "CMA FMC VFC ILMN CTLT GL MHK MOS RHI HSIC DVA"
).split()

RUSSELL2000_EXPANSION_TICKERS = (
    "SMCI CELH ELF MARA RIOT UPST FUBO CHPT RUN ENVX STEM LC LMND OPEN RKT SOFI "
    "AFRM DKNG HOOD NIO AMC GME BB PLTR RIVN LCID IONQ DNA AI CAVA DUOL CART BROS "
    "BIRK TOST PATH BILL DOCN APPF ALKT MQ UPWK FIVN ZI ASAN COUR RBLX OSCR HIMS "
    "RXRX CRSP BEAM EDIT NTLA VERV BLUE ARCT SANA PACB TWST SDGR VRNA ALLO FATE "
    "CLOV ROOT LMND BFLY ACHR JOBY EVGO BLNK QS NKLA GOEV FFIE WKHS ARVL PSNY "
    "OUST LAZR INVZ AEVA MVIS AUR GETY VLD DM MTTR SPCE RKLB ASTR LUNR RDW "
    "ASTS SATL IRDM GSAT MAXR LTHM PLL MP ENVX FREY SLDP STEM AMPX FLNC NOVA "
    "ARRY SHLS BE SPWR FSLR ENPH SEDG RUN PLUG FCEL BLDP BEEM SUNW ORGN DNA "
    "TWLO ESTC MDB DDOG NET SNOW OKTA ZS CRWD S HCP GTLB SMAR CFLT NCNO FRSH "
    "AMPL PD WK ME ASLE YOU ALIT PAYO SOUN BBAI CXAI GRRR PI INOD RGTI QBTS "
    "BKSY PLAN COMP RDFN OPEN UWMC RKT TREE LC UPST AFRM SQSP WIX YELP FVRR "
    "ETSY REAL POSH RENT TDOC AMWL DOCS VEEV HQY HCAT CERT INSP NVAX MRNA INO "
    "VIR BNTX SAVA AXSM MDGL VKTX IOVA TGTX IMVT ARWR RARE SRPT DNLI CGEN "
    "GERN KURA XENE KYMR HALO BPMC EXEL IONS MRTX MORF"
).split()

SP500_SUPPLEMENT_TICKERS = (
    "AAL ALGN ALK ALLE AMCR ATO AVY BKR BXP CAG CCL CHRW CNC CPT DAY DOC DLR "
    "DRI EG ED EVRG EXPD FRT GLW HRL HSY JBHT KMX KIM KMI KSS LNT LW LVS MCD "
    "MGM NCLH NI NRG PFG PKG PNR PNW PPG PXD REG ROK ROP SBAC SLB TAP TDY TPR "
    "TYL UDR UHS VICI VRSN WAT WBD WHR WRK WTW WYNN XEL ZBRA ZION APTV HII "
    "JNPR FFIV QRVO CDAY ETSY PARA SEE BFB CPB NKE UPS LOW ROST TJX RL "
    "TPR PVH NWS FOXA LKQ LKQ CTRA EQT MRO APA DVN FANG HAL BKR SLB VTRS "
    "INCY UHS WST RGEN COO PODD DXCM HOLX ALGN BDX COO BAX ZBH XRAY DVA"
).split()

RUSSELL2000_SUPPLEMENT_TICKERS = (
    "AAOI ACIW ACAD ADMA AEHR AEO AGIO AKRO ALGT AMBA AMKR ANF APPS ARDX ARHS "
    "ASO ATGE AVAV AXNX BANC BCRX BEAM BERY BGC BL BMBL BOOT BOX BRZE CALX "
    "CAR CRNC CRSR CWH DDD DLO DNUT DOCS DOCU DOMO DORM EAT EBC ECPG EFC "
    "ENOV EOSE EPRT EVH EXAS FCFS FLGT FROG FTAI GBTG GCT GDRX GLBE GOGO "
    "GTLB HAIN HAYW HIMS IAC IART INDI INMD INST IRBT ITCI JAZZ KD KLIC KTB "
    "LAUR LITE LPRO LTH MANU MATX MGNI MODG MRCY MSTR NARI NFE NTNX NVST OLO "
    "OPCH OSW PAGS PAR PATH PAY PRO PRVA PTON PUBM RAMP RARE RBLX REZI RGEN "
    "ROKU RPD RUN SAIA SANA SEMR SGH SHOO SITM SKYW SLAB SMTC SONO SPNS SPWR "
    "SSTK TALO TNDM TNET TREX TSEM TTEC TTGT UDMY UPBD USFD VCEL VERX VRNS "
    "WING WK XPER YETI ZETA ZM ZUO"
).split()


def expanded_population_tickers(name: str, editable_tickers: tuple[str, ...]) -> tuple[str, ...]:
    normalized = name.strip().lower()
    if normalized == "qqq":
        return _dedupe(tuple(editable_tickers) + tuple(QQQ_EXPANSION_TICKERS))
    if normalized == "sp500":
        return _dedupe(tuple(editable_tickers) + tuple(SP500_EXPANSION_TICKERS) + tuple(SP500_SUPPLEMENT_TICKERS))
    if normalized == "russell2000":
        return _dedupe(tuple(editable_tickers) + tuple(RUSSELL2000_EXPANSION_TICKERS) + tuple(RUSSELL2000_SUPPLEMENT_TICKERS))
    return _dedupe(editable_tickers)


def classify_market_archetype(
    ticker: str,
    market_cap: float | None = None,
    memberships: tuple[str, ...] = (),
) -> str:
    symbol = ticker.strip().upper()
    if symbol in MEME_TICKERS:
        return ARCHETYPE_MEME
    if symbol in SPECIAL_SITUATION_TICKERS:
        return ARCHETYPE_SPECIAL_SITUATION
    if market_cap is not None and market_cap > 0:
        if market_cap >= 1_000_000_000_000:
            return ARCHETYPE_MEGA
        if market_cap >= 10_000_000_000:
            return ARCHETYPE_LARGE
        if market_cap >= 2_000_000_000:
            return ARCHETYPE_MID
        if market_cap >= 300_000_000:
            return ARCHETYPE_SMALL
        return ARCHETYPE_MICRO
    if "qqq" in memberships or "sp500" in memberships:
        return ARCHETYPE_LARGE
    if "russell2000" in memberships:
        return ARCHETYPE_SMALL
    if "micro_moonshot" in memberships:
        return ARCHETYPE_MICRO
    return ARCHETYPE_SMALL


def _dedupe(tickers: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(ticker.strip().upper() for ticker in tickers if ticker.strip()))
